script: "bundle exec rspec spec"
before_install:
  - "apt-get install ruby-dev libtag1-dev"

language: ruby
rvm:
  - 2.1.1

branches:
  only:
    - master

notifications:
  email:
    - eugene.pempel@gmail.com
