language: ruby
rvm:
  - 2.1.1
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install ruby-dev libtag1-dev
bundler_args: --without development
script: "bundle exec rspec spec"
branches:
  only:
    - master
notifications:
  email:
    - eugene.pempel@gmail.com
